### ISSUE TITLE
Create a 3D Digital Human Issues

### ISSUE THREAD

**Issue by Praveenansurya** [YnotZer0/unity3d_watsonSdk#4]
Hi Tony,

Thanks for being nicer. Sorry we could put the question properly as we are not developers. We are a group of facial modellers trying to explore this area and convert it into business going forward. Your article is very helpful to build a quick prototype.

Platform : macos seirra version 10.12.6
Unity version: Unity 2018.3.3f1
Yes we followed the instructions for digital avatar and install worked
We bought Salsa and install worked.
Installed IBM SDK and install worked and imported into Assets.
![screen shot 2019-02-10 at 10 13 04 pm](https://user-images.githubusercontent.com/47501817/52536492-4ef1a080-2d81-11e9-8103-e3f3bbc79bcc.png)

We reached till Setup unity 3d and we were able to add a canvas text game object to display " welcome to Watson" message.

When we were adding all the components to game object we got compilation errors.

![screen shot 2019-02-10 at 10 22 53 pm](https://user-images.githubusercontent.com/47501817/52536577-7006c100-2d82-11e9-90bd-ec94137dadcb.png)

Also, we the watson script didn't load automatically. In section: 
![screen shot 2019-02-10 at 10 34 58 pm](https://user-images.githubusercontent.com/47501817/52536713-29b26180-2d84-11e9-8c63-fb3fe2147043.png)

You asked to ensure to add Watson script. but we couldn't get the details to add it that section of yours.

Compilation errors:

![screen shot 2019-02-10 at 10 41 40 pm](https://user-images.githubusercontent.com/47501817/52536871-f40e7800-2d85-11e9-8767-6edeb03ba41a.png)

**Comment by YnotZer0** [comment]
hmmmm...judging by the second screenshot, all of your scripts are failing and the third screenshot is showing that the errors are basic C# values, nothing specific to the actual code, therefore there is something else fundamentally incorrect in your project setup.

Are you able to upload your project to a dropbox/Box/cloud folder so that I can download it and take a look at your setup?  Or, I can provide you with a Box link to my project (compressed) and you can then import that into Unity and compare the differences with your setup of the project?

Let me know which is easier - probably best for me to email you a Box folder link rather than paste it here.

thanks tony

**Comment by Praveenansurya** [comment]
Hi Tony,

Thanks for replying, it would be great if you email a box folder, we can
compare and see where we went wrong.

Regards,
Praveen


---------- Forwarded message ---------

**Comment by Praveenansurya** [comment]
Emailing box folder would be easier. Thanks Tony.

**Comment by YnotZer0** [comment]
I'd need to know a (temp) email address to send the box folder link to.  thanks tony

**Comment by Praveenansurya** [comment]
anasuryapraveen@gmail.com

**Comment by Praveenansurya** [comment]
anasuryapraveen@gmail.com

**Comment by YnotZer0** [comment]
Hi Praveen,  did you figure it out from what I shared?

**Comment by Praveenansurya** [comment]
Hi Tony,

Sorry for the late reply. We did some good progress after repeatedly
importing assets but we still are facing some problems in loading watsonTTS
script. I am attaching the screenshots to give you a more clearer picture:

1.
While adding new component, We couldn't find WatsonTTS.cs or
Watson_newServices.cs.

[image: 52951186_2278199685724852_6066938435732504576_n.png]

In which we could only find Example Assistant V2.
[image: 53037363_409554519833337_4260889041198645248_n.png]
[image: 53723717_251142202499564_504429726933188608_n.png]
[image: 53067895_800888170261412_5817788718626373632_n.png]

We did get the avatar this time while running but unable to start the
conversation.
[image: 53139516_385243515600163_7912399966297915392_n.png]


[image: 53037363_409554519833337_4260889041198645248_n.png]

Regards,
Praveen

**Comment by YnotZer0** [comment]
Images did not show in your message?

As to importing assets - you may have to import the Salsa asset twice, I noticed for some odd reason it didn't pick up the sample code on the first import, so doing it twice it appears.

Okay, well, if you want the UMA Digital Human to actually do something, you need to follow the article and create the empty Watson_newService.cs file and then copy the content from this github into the file.  That is something that you have to manually add to the project (that I've already written for you).
If you are creating Watson services (STT,TSS,WA) new, ie. since November 2018 then use the Watson_newService.cs file as this contains the way to use the new IAM security APIKey.

thanks tony

**Comment by Praveenansurya** [comment]
Hi Tony,

Thanks for the help, Now we are able to create the watson services and
inserted APIkey and urls, but when we click the play button and run, the
end result is still same, the character doesn't talk. Sorry for the
trouble, but with your help we could reach so far, I guess we are almost
there but missing something.

Regards,
Praveen

**Comment by YnotZer0** [comment]
Well, I've tried the best I can, having shared the entire project for just loading into Unity - if that doesn't work for you, then there is something else wrong with the environment itself and is therefore outside of the scope of anything I can probably assist you with.  I know that the article and project itself does work beyond just my setup, numerous people have contacted me and some have even shared their Unity projects where they have even gone further and extended to use VR within Unity, therefore all I can conclude is that there is something about your installation/setup/configuration that is preventing you from the full experience.  I would suggest deleting your Unity environment completely and starting again from fresh, but may be you have already tried that.  Sorry, I could not be of any more help.
